### ISSUE TITLE
The node with key '---' may not add a route value with the key 'title' and value '---' to the RouteValues dictionary because the key is a reserved name. Reserved names are keys that are meant for use internally by MvcSiteMapProvider rather than a dictionary value.

### ISSUE THREAD

**Issue by Mds92** [maartenba/MvcSiteMapProvider#373] opened 2014-11-27 10:28 UTC
I've installed the following packages :
`MvcSiteMapProvider.MVC5   4.6.17`
`MvcSiteMapProvider.MVC5.Core   4.6.17`
`MvcSiteMapProvider.Web   4.6.17`

I'm using MvcSiteMapProvider with the following code:
<pre>foreach (ContentModel content in allContents.Where(q => q.StatusId == (int)ContentStatusEnum.Confirmed).OrderByDescending(q => q.RegistrationDate))
{
    LanguageModel language = allLanguages.First(q => q.Id == content.LanguageId);
    DynamicNode dynamicNode = new DynamicNode
    {
        Title = content.Title,
        Route = "ContentLink",
        Controller = "Content",
        Action = "Index",
        RouteValues = new Dictionary<string, object>(),
        LastModifiedDate = content.RegistrationDate,
        ChangeFrequency = ChangeFrequency.Daily,
        ImageUrl = content.ImagePath,
    };
    dynamicNode.RouteValues.Add("title", content.Title.RemoveIllegalCharsForUrl());
    dynamicNode.RouteValues.Add("id", content.Id);
    dynamicNode.RouteValues.Add("language", language.Name);
    dynamicNodes.Add(dynamicNode);
}</pre>

but the following exception has occurred:
`The node with key '7bad30ad-50a4-401f-9b28-11be8e723f15' may not add a route value with the key 'title' and value 'some tile' to the RouteValues dictionary because the key is a reserved name. Reserved names are keys that are meant for use internally by MvcSiteMapProvider rather than a dictionary value.`

`Valid keys may be "area", "controller", "action", and custom parameters that are not the same as property names of ISiteMapNode.`

`You may suppress this error message by calling an overload of the RouteValues.Add() or RouteValues.AddRange() that accepts the 'throwIfReservedKey' argument and passing false for the value. Note that if you do this, attempting to add a key with a reserved name to the RouteValues dictionary will silently fail.`

What's wrong, how can I fix it?

**Comment by NightOwl888** [comment] 2015-01-30 16:47
Closing this issue because it is a duplicate of #346.

**Closed by NightOwl888** 2015-01-30 16:47 UTC
Labels: is:Duplicate
