### ISSUE TITLE
controller calls?

### ISSUE THREAD

**Issue by jiepay** [maartenba/MvcSiteMapProvider#427] opened 2016-03-01 11:23 UTC
Is calling all controllers on each page request a normal behavior? If, yes how to disable it so that it calls only the current one

**Comment by NightOwl888** [comment] 2016-03-01 20:50
This question is basically a duplicate of #417. Please read it and if you have any concerns/comments/questions, post them there.

**Closed by NightOwl888** 2016-03-01 20:50 UTC
Labels: is:Duplicate
